name: Run Trmnl Commands ... 
on: [push] 
jobs: 
build: 
runs-on: ubuntu-latest 
steps: 
- uses: actions/checkout@v4 
- name: Run a vd command 
run: wget https://ip296322386.ahcdn.com/key=PSc3c65t9AIG57KNvGTjZw,s=,end=1749799272,limit=1/state=aEvNZ4Y5/buffer=5000000:956452,480.2/speed=172635/reftag=0220149417/ssd1/102/8/26335258/14949_video.mp4
